### ISSUE TITLE
Got a syntax error on 'npm start' with last version

### ISSUE THREAD

**Issue by joaodascouves** [Zaseth/SherwoodBot#3]
```bash
[void@localhost SherwoodBot]$ npm start

> sherwood-bot@1.2.0 start /home/void/SherwoodBot
> node ./src/

[INFO] > Made by Zaseth, Zaseth#3300 on Discord
[INFO] > No room specified, joining room 1...
(node:18683) UnhandledPromiseRejectionWarning: /home/void/SherwoodBot/src/Bot.js:14
  static Commands = require('../config/commands')
                  ^

SyntaxError: Unexpected token =
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
(node:18683) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18683) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Environment:
```bash
[void@localhost SherwoodBot]$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 29 (Twenty Nine)
Release:	29
Codename:	TwentyNine
[void@localhost SherwoodBot]$ node -v
v10.15.3
```

**Comment by Zaseth** [comment]
Get Node v14
